#!/usr/bin/env bash
# SSH client configuration must use the private key ~/.ssh/school
# SSH client configuration must refuse to authenticate using a password

Host 107.21.139.186
     PasswordAuthentication no
     IdentityFile ~/.ssh/school
