#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server


sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  cgyireh1_frontend
        bind *:80
        mode http
        default_backend cgyireh1_backend
backend cgyireh1_backend
        balance roundrobin
        server 5661-web-01 54.226.99.242:80 check
        server 5661-web-02 54.87.0.55:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
