#!/usr/bin/env bash
# Install nginx on web server


sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw "Nginx HTTP"

echo "Holberton School" | sudo tee /var/www/html/index.html


sudo nginx -t

sudo service nginx restart
