#!/usr/bin/env bash
#  Configures a new Ubuntu machine to Perform a 301-redirection

sudo apt-get update
sudo apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.html

rep_str="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/cgyireh1 permanent;"
sudo sed -i "s/server_name _;/$rep_str/" /etc/nginx/sites-enabled/default

sudo service nginx restart
