#!/usr/bin/env bash
# 301 Moved Permanently

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html

replacement_str="server_name _;\n\trewrite ^\/redirect_me https:x\/\/github.com\/cgyireh1 permanent;"

sudo sed -i "s/server_name _;/$replacement_str" /etc/nginx/sites-enabled/default
service nginx restart
